format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$nodejs\
$java\
$docker_context\
$cmd_duration\
$line_break\
$character"""

[username]
style_user = "bold #bb78a7"
disabled = true
show_always = true
format = "[$user ]($style)"

[hostname]
ssh_only = true

[directory]
format = "[$path]($style fg:#5e81ac) "
read_only = " "

[character]
success_symbol = "[❯](bold #5e81ac)"
error_symbol = "[✗](#bf616a)"